# Generated by Django 3.0.3 on 2020-03-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleryApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60, null=True)),
                ('username', models.CharField(max_length=60)),
                ('birthdate', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Maried', 'Maried'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('In A Relationship', 'In A Relationship')], max_length=18, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('bio', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('details', models.CharField(max_length=200, null=True)),
                ('numberplate', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryApp.Brand')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryApp.Bike')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myProfileApp.UserProfile')),
            ],
        ),
    ]
