# Generated by Django 3.0.3 on 2020-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0004_auto_20200329_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pics'),
        ),
    ]
